//! `handler` — multi-path WASI Preview 2 wasi:http/incoming-handler.
//!
//! Used by Phase E L1–L10 integration tests. Implemented in Rust with
//! `wit-bindgen 0.57` (the version wasmtime 25.0.3 transitively pulls in).
//!
//! ## Paths
//!
//! | Path        | Behavior                                |
//! |-------------|-----------------------------------------|
//! | `GET /`     | 200, body `{"hello":"handler"}`         |
//! | `GET /busy` | Busy-loops a counter for ~5s of Wasm    |
//!
//! All other paths return 404.
//!
//! The /busy path is critical for L7 (per-request timeout). It must
//! burn CPU in the guest rather than calling `edge:cloud/time::sleep`
//! (which is `tokio::time::sleep` and does not yield to the epoch
//! ticker — verified in `edge-runtime/src/interfaces/time.rs:19-23`).
//!
//! ## Future expansion
//!
//! Phase D landed only `/` and `/busy` so the L1–L4 + L5 + L7 tests
//! have a working FaaS surface. The kv/egress/fs paths from the
//! earlier draft are deferred to a follow-up PR — they each have
//! their own test (L6, L9, L10) and the
//! `edge:cloud/kv-store`/`wasi:filesystem`/`wasi:http/outgoing-handler`
//! binding gymnastics are out of scope for the v0.2 cut.

#![no_main]

// `generate_all` pulls in every transitive `wasi:*` interface so we
// don't have to enumerate each one in a `with:` map.
wit_bindgen::generate!({
    world: "edge-runtime-handler",
    path: "../wit",
    generate_all,
});

// The `Guest` trait is generated by wit-bindgen from the world's
// exports. The `wasi:http/incoming-handler` export lives under
// `exports::wasi::http::incoming_handler::Guest`.
use crate::exports::wasi::http::incoming_handler::Guest;

// Re-export the wasi:http types at the crate root for ergonomic use.
use crate::wasi::http::types::{
    Fields, IncomingRequest, Method, OutgoingResponse, ResponseOutparam,
};

struct Component;
export!(Component);

// The `wasi:cli/command` world (which our world `include`s) exports
// `wasi:cli/run`. We don't use it for the FaaS path — wasi:http/
// incoming-handler is the actual entry point — but the macro
// requires us to implement the trait. Trap-on-call is the safe
// default: a guest that ends up here has been dispatched wrong.
impl crate::exports::wasi::cli::run::Guest for Component {
    fn run() -> Result<(), ()> {
        unreachable!("wasi:cli/run should not be called for a FaaS component")
    }
}

impl Guest for Component {
    fn handle(req: IncomingRequest, out: ResponseOutparam) {
        let path = req.path_with_query().unwrap_or_else(|| "/".to_string());
        let method = req.method();

        if matches!(method, Method::Get) {
            if path == "/" {
                return_json(out, 200, br#"{"hello":"handler","path":"/"}"#);
                return;
            }
            if path == "/busy" {
                return_busy_then_ok(out);
                return;
            }
        }
        return_json(out, 404, br#"{"error":"not found"}"#);
    }
}

fn return_json(out: ResponseOutparam, status: u16, body: &[u8]) {
    let headers = Fields::new();
    let _ = headers.set(&"content-type".to_string(), &[b"application/json".to_vec()]);
    let resp = OutgoingResponse::new(headers);
    resp.set_status_code(status).unwrap();
    let body_handle = resp.body().expect("response body");
    let stream = body_handle.write().expect("output stream");
    stream.blocking_write_and_flush(body).unwrap();
    drop(stream);
    // The macro generates `finish` and `set` as associated functions
    // rather than methods; use the UFCS form.
    let _ = crate::wasi::http::types::OutgoingBody::finish(body_handle, None);
    crate::wasi::http::types::ResponseOutparam::set(out, Ok(resp));
}

/// Busy loop — calibrated to exceed ~5s of Wasm execution at default
/// 1ms epoch ticks. A 100ms budget will trap this at the 10th tick.
fn return_busy_then_ok(out: ResponseOutparam) {
    let mut counter: u64 = 0;
    for i in 0u64..5_000_000_000 {
        counter = counter.wrapping_mul(31).wrapping_add(i);
    }
    // Prevent the optimizer from eliminating the loop.
    core::hint::black_box(counter);
    return_json(out, 200, br#"{"slept":"~5s in Wasm"}"#);
}
